
export const LS_KEYS = {
    MAIN_TAB: 'wakfarm_mainTab',
    EXPANDED_RUN: 'wakfarm_expanded_run',
    // Prix collectifs (P2P)
    PRICES_COLLECTIVE_TAB: 'wakfarm_prices_collective_tab',
    PRICES_COLLECTIVE_SEARCH_NAME: 'wakfarm_prices_collective_searchName',
    PRICES_COLLECTIVE_RARITIES: 'wakfarm_prices_collective_rarities',
    PRICES_COLLECTIVE_LEVEL_MIN: 'wakfarm_prices_collective_levelMin',
    PRICES_COLLECTIVE_LEVEL_MAX: 'wakfarm_prices_collective_levelMax',
    PRICES_COLLECTIVE_SORT_COLUMN: 'wakfarm_prices_collective_sortColumn',
    PRICES_COLLECTIVE_SORT_DIRECTION: 'wakfarm_prices_collective_sortDirection',
    PRICES_COLLECTIVE_PAGE: 'wakfarm_prices_collective_page',
    PRICES_COLLECTIVE_PER_PAGE: 'wakfarm_prices_collective_perPage',
    PRICES_COLLECTIVE_INSTANCES: 'wakfarm_prices_collective_instances',
    // Prix collectifs locaux (avant P2P)
    LOCAL_COLLECTIVE_PRICES: 'wakfarm_local_collective_prices',
    // Prix personnels (local)
    PERSONAL_PRICES: 'wakfarm_personal_prices',
    PRICES_PERSONAL_SEARCH_NAME: 'wakfarm_prices_personal_searchName',
    PRICES_PERSONAL_RARITIES: 'wakfarm_prices_personal_rarities',
    PRICES_PERSONAL_LEVEL_MIN: 'wakfarm_prices_personal_levelMin',
    PRICES_PERSONAL_LEVEL_MAX: 'wakfarm_prices_personal_levelMax',
    PRICES_PERSONAL_SORT_COLUMN: 'wakfarm_prices_personal_sortColumn',
    PRICES_PERSONAL_SORT_DIRECTION: 'wakfarm_prices_personal_sortDirection',
    PRICES_PERSONAL_PAGE: 'wakfarm_prices_personal_page',
    PRICES_PERSONAL_PER_PAGE: 'wakfarm_prices_personal_perPage',
    PRICES_PERSONAL_INSTANCES: 'wakfarm_prices_personal_instances',
    RUNS_SUBTAB: 'wakfarm_runs_subTab',
    EXPANDED_HOUR_RUNS: 'wakfarm_expanded_hour_runs',
    TIME_PERIOD: 'wakfarm_time_period',
    SETTINGS_FOLDER_PATH: 'settings.folderPath',
    SETTINGS_LAUNCH_ON_STARTUP: 'settings.launchOnStartup',
    SETTINGS_MINIMIZE_TO_TRAY: 'settings.minimizeToTray',
    CONFIG_RUNS: 'wakfarm_configs',
    CONFIG_RUNS_EXPANDED: 'wakfarm_configs_expanded',
    CONFIG: 'wakfarm_config_v1',
    LANGUAGE: 'wakfarm_language',
    EXPANDED_INSTANCES: 'expandedInstances_v1',
    DETAILED_VIEW: 'wakfarm_detailed_view',
}