
export const LS_KEYS = {
    MAIN_TAB: 'wakfarm_mainTab',
    EXPANDED_RUN: 'wakfarm_expanded_run',
    PRICES_SEARCH_NAME: 'wakfarm_prices_searchName',
    PRICES_RARITIES: 'wakfarm_prices_rarities',
    PRICES_LEVEL_MIN: 'wakfarm_prices_levelMin',
    PRICES_LEVEL_MAX: 'wakfarm_prices_levelMax',
    PRICES_SORT_COLUMN: 'wakfarm_prices_sortColumn',
    PRICES_SORT_DIRECTION: 'wakfarm_prices_sortDirection',
    PRICES_PAGE: 'wakfarm_prices_page',
    PRICES_PER_PAGE: 'wakfarm_prices_perPage',
    PRICES_INSTANCES: 'wakfarm_prices_instances',
    RUNS_SUBTAB: 'wakfarm_runs_subTab',
    EXPANDED_HOUR_RUNS: 'wakfarm_expanded_hour_runs',
    TIME_PERIOD: 'wakfarm_time_period',
    SETTINGS_FOLDER_PATH: 'settings.folderPath',
    SETTINGS_DELETE_AFTER_OCR: 'settings.deleteAfterOCR',
    SETTINGS_LAUNCH_ON_STARTUP: 'settings.launchOnStartup',
    SETTINGS_MINIMIZE_TO_TRAY: 'settings.minimizeToTray',
    CONFIG_RUNS: 'wakfarm_configs',
    CONFIG_RUNS_EXPANDED: 'wakfarm_configs_expanded',
    CONFIG: 'wakfarm_config_v1',
    LANGUAGE: 'wakfarm_language',
    EXPANDED_INSTANCES: 'expandedInstances_v1',
    DETAILED_VIEW: 'wakfarm_detailed_view',
}